# Stage 1
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=production

RUN npm install

COPY . .

# Stage 2
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 5001

CMD ["npm","start"]
