kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  namespace: chat-app
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
